package scheduler

import (
	"context"
	"fmt"
	"log"
	"time"

	"github.com/robfig/cron/v3"
	"github.com/shopflow/analytics-service/internal/repository"
	"github.com/shopflow/analytics-service/telemetry"
	"go.opentelemetry.io/otel/attribute"
	"go.opentelemetry.io/otel/codes"
	"go.opentelemetry.io/otel/metric"
)

var (
	reportsGenerated metric.Int64Counter
	reportDuration   metric.Float64Histogram
)

func initMetrics() {
	meter := telemetry.Meter("analytics-service/scheduler")
	reportsGenerated, _ = meter.Int64Counter(
		"analytics.reports.generated.total",
		metric.WithDescription("Total sales reports generated by cron"),
	)
	reportDuration, _ = meter.Float64Histogram(
		"analytics.report.generation.duration.seconds",
		metric.WithDescription("Time taken to generate a sales report"),
		metric.WithUnit("s"),
	)
}

func StartScheduler(ctx context.Context, intervalSeconds int) *cron.Cron {
	initMetrics()

	c := cron.New(cron.WithSeconds())
	schedule := formatSchedule(intervalSeconds)

	c.AddFunc(schedule, func() {
		generateReport(ctx)
	})

	c.Start()
	log.Printf("Sales report scheduler started — running every %d seconds", intervalSeconds)
	return c
}

func generateReport(ctx context.Context) {
	tracer := telemetry.Tracer("analytics-service/scheduler")

	ctx, span := tracer.Start(context.Background(), "scheduler.generate_sales_report")
	defer span.End()

	span.SetAttributes(
		attribute.String("job.name", "sales_report"),
		attribute.String("job.trigger", "cron"),
	)

	start := time.Now()
	log.Println("Generating sales report...")

	report, err := repository.GenerateSalesReport(ctx)
	duration := time.Since(start).Seconds()

	reportDuration.Record(ctx, duration)

	if err != nil {
		log.Printf("Failed to generate sales report: %v", err)
		span.RecordError(err)
		span.SetStatus(codes.Error, err.Error())
		return
	}

	reportsGenerated.Add(ctx, 1)
	span.SetAttributes(
		attribute.Int("report.total_orders", report.TotalOrders),
		attribute.Float64("report.total_revenue", report.TotalRevenue),
		attribute.String("report.top_product", report.TopProduct),
	)
	span.SetStatus(codes.Ok, "report generated")

	log.Printf("Sales report generated: orders=%d revenue=%.2f top_product=%s duration=%.3fs",
		report.TotalOrders, report.TotalRevenue, report.TopProduct, duration)
}

func formatSchedule(seconds int) string {
	return fmt.Sprintf("*/%d * * * * *", seconds)
}
